# Generated by Django 4.0.4 on 2022-05-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('select', 'select')], default='radio', max_length=10),
        ),
    ]
